name: Build

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]

permissions:
  contents: write # This covers releases since they're repository contents

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller build.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: glaze-autotiler-${{ runner.os }}
          path: dist/glaze-autotiler.exe

      # Create Release when a tag is pushed
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/glaze-autotiler.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
